//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillItemType
    {
        public BillItemType()
        {
            this.BillableItems = new HashSet<BillableItem>();
        }
    
        public int BillItemID { get; set; }
        public string BillItemDesc { get; set; }
    
        public virtual ICollection<BillableItem> BillableItems { get; set; }
    }
}
