//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillItem
    {
        public int BillItemID { get; set; }
        public Nullable<int> BillableItemID { get; set; }
        public Nullable<decimal> BillItemAmmount { get; set; }
        public Nullable<int> BillId { get; set; }
    
        public virtual BillableItem BillableItem { get; set; }
        public virtual Bill Bill { get; set; }
    }
}
