//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillableItem
    {
        public BillableItem()
        {
            this.BillItems = new HashSet<BillItem>();
        }
    
        public int BillableItemID { get; set; }
        public Nullable<int> BillableItemType { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> ActiveBillableItem { get; set; }
    
        public virtual BillItemType BillItemType { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<BillItem> BillItems { get; set; }
    }
}
