//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reading
    {
        public int ReadingID { get; set; }
        public Nullable<System.DateTime> ReadingDate { get; set; }
        public Nullable<decimal> ReadingValue { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> ReadingVariance { get; set; }
        public Nullable<int> BillMonthID { get; set; }
    
        public virtual BillMonth BillMonth { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
