//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rover.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoverEntities : DbContext
    {
        public RoverEntities()
            : base("name=RoverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillableItem> BillableItems { get; set; }
        public virtual DbSet<BillItem> BillItems { get; set; }
        public virtual DbSet<BillItemType> BillItemTypes { get; set; }
        public virtual DbSet<BillMonth> BillMonths { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Reading> Readings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UnitType> UnitTypes { get; set; }
    }
}
