//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.BillableItems = new HashSet<BillableItem>();
            this.Bills = new HashSet<Bill>();
            this.Readings = new HashSet<Reading>();
            this.Units1 = new HashSet<Unit>();
        }
    
        public int UnitID { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> UnitTypeID { get; set; }
        public Nullable<int> UnitParentID { get; set; }
        public Nullable<int> UnitNumber { get; set; }
    
        public virtual ICollection<BillableItem> BillableItems { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<Reading> Readings { get; set; }
        public virtual ICollection<Unit> Units1 { get; set; }
        public virtual Unit Unit1 { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
